sudo: false
language: node_js
node_js:
  - 8
  - 9
  - 10
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
env:
  global:
    - CC=gcc-6
    - CXX=g++-6
script:
  - npm run ci
