version: 2
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0-buster
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: test
          command: npm run ci
