version: 2
jobs:
  build:
    docker:
      - image: circleci/node:13.10.0-buster
    steps:
      - checkout
      - run:
          name: install
          command: |
            sudo apt -y install lcov
            npm install
      - run:
          name: test
          command: npm run ci
